In [1]:
#!pip install tensorflow

import tensorflow as tf

print("TensorFlow Version:", tf.__version__)

a = tf.constant(5)
b = tf.constant(10)

print(a)
print(b) 

print("Addition:", tf.add(a, b))
print("Subtraction:", tf.subtract(a, b))
print("Multiplication:", tf.multiply(a, b))
print("Division:", tf.divide(a, b))

TensorFlow Version: 2.21.0
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
Addition: tf.Tensor(15, shape=(), dtype=int32)
Subtraction: tf.Tensor(-5, shape=(), dtype=int32)
Multiplication: tf.Tensor(50, shape=(), dtype=int32)
Division: tf.Tensor(0.5, shape=(), dtype=float64)


In [2]:
x = tf.constant([[1, 2], [3, 4]])
y = tf.constant([[5, 6], [7, 8]])

print("Matrix Addition:", tf.add(x, y))
print("Matrix Multiplication:", tf.matmul(x, y))

print("Shape of x:", x.shape)
print("Data type of x:", x.dtype)

Matrix Addition: tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Matrix Multiplication: tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
Shape of x: (2, 2)
Data type of x: <dtype: 'int32'>


In [3]:
t = tf.constant([1, 2, 3, 4])

print("First element of t:", t[0])
print("Slice of t:", t[1:3])

reshaped = tf.reshape(t, (2, 2))
print("Reshaped Tensor:\n", reshaped)

rand = tf.random.uniform((2, 2))
print("Random Tensor:\n", rand)

c = tf.cast(a, tf.float32)
print("Type casted tensor:", c)

First element of t: tf.Tensor(1, shape=(), dtype=int32)
Slice of t: tf.Tensor([2 3], shape=(2,), dtype=int32)
Reshaped Tensor:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Random Tensor:
 tf.Tensor(
[[0.473194   0.37026155]
 [0.8998203  0.88597405]], shape=(2, 2), dtype=float32)
Type casted tensor: tf.Tensor(5.0, shape=(), dtype=float32)


In [4]:
print("Sum:", tf.reduce_sum(t))
print("Mean:", tf.reduce_mean(t))
print("Max:", tf.reduce_max(t))
print("Min:", tf.reduce_min(t))


Sum: tf.Tensor(10, shape=(), dtype=int32)
Mean: tf.Tensor(2, shape=(), dtype=int32)
Max: tf.Tensor(4, shape=(), dtype=int32)
Min: tf.Tensor(1, shape=(), dtype=int32)
